#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<string.h>
#include<math.h>
#define NUM_LETTERS 26 // Number of letters in the English alphabet

double mean(const int arr[], int size) {
    double sum = 0;
    for (int i = 0; i < size; i++) {
        sum += arr[i];
    }
    return sum / size;
}

double variance(const int arr[], int size, double mean) {
    double sum = 0;
    for (int i = 0; i < size; i++) {
        sum += (arr[i] - mean) * (arr[i] - mean);
    }
    return sum / size;
}

int mode(const int arr[], int size) {
    int maxValue = 0, maxCount = 0;

    for (int i = 0; i < size; ++i) {
        int count = 0;
        for (int j = 0; j < size; ++j) {
            if (arr[j] == arr[i]) ++count;
        }
        
        if (count > maxCount) {
            maxCount = count;
            maxValue = arr[i];
        }
    }
    return maxValue;
}

// Function to guess the key length of a Vigenère cipher
int guess_key_length(const char* cipher) {
    int length = strlen(cipher);
    int* res = (int*)malloc(length * sizeof(int));

    // Count matching characters for each possible shift
    for (int shift = 0; shift < length; shift++) {
        int matches = 0;
        for (int i = 0; i < length; i++) {
            if (cipher[i] == cipher[(i - shift + length) % length]) {
                matches++;
            }
        }
        res[shift] = matches;
    }

    double dat_means = mean(res + 1, length - 1);
    double dat_std_dev = sqrt(variance(res + 1, length - 1, dat_means));

    // Find peaks
    int* peaks = (int*)malloc(length * sizeof(int));
    int peaks_count = 0;
    for (int i = 0; i < length; i++) {
        if (res[i] >= dat_std_dev + dat_means) {
            peaks[peaks_count++] = i;
        }
    }

    // Calculate differences between peaks
    int* peak_diff = (int*)malloc((peaks_count - 1) * sizeof(int));
    for (int i = 0; i < peaks_count - 1; i++) {
        peak_diff[i] = peaks[i + 1] - peaks[i];
    }

    int key_length = mode(peak_diff, peaks_count - 1);

    free(res);
    free(peaks);
    free(peak_diff);

    return key_length;
}




int main()
{
    char* encrypted = "CXYFNEPVNITAKXGGXMQUKPAMVERWNEQLRIQIEEPWBSMLYJRZOZYJSELUOEJLOVLSDMTWVCGLSWASVGSDKXCVLCDAXHGFQXFWWIYFYJYVKXYKOXDAXHGFQXFWNMDXOVCFMIMXOEAZNERSZSGFDXMLRIKWKRQIEEPAXKRZOHGXPIPWXGCKKHBAXKRZOQRGQIRZOVBAFMBAXKZQDLCFEQZWBSDHYMLLCMLLRIBSDEQWDPCKCELVPMLVSRELRIQIEEPWBSMLCXYFNEPVNITAKXGGXMQAWTMJDELLLIASEWCADGYFRIJHEWCJCEQKOWQJSWIUYRQANIPSXMLNOWREORRGZXGGXAGLRELSFIPSQIYFXYYDBIRMBRMXZIPQOEPZYACNOVRZSWYNOVYYOAYKNIPAFIBXBSKLRINSCXRZBICQOEPJOXSJXWMXWELQFEJMOWZQMEJUEPYLSRELRIQLKRBSBHBWFMYLSSLSXHSFNIPKDELVSREQYYPDYAJAUIJARSMVYJYUDYYDVCYNOVYYSREAXELQCMLYVIEAFILQOEPQYYPTOXRWBEPEOHRGWEIWSRDGBQCVNIAACMMFCELVBIAGQRGRSREMXHCJVCGFQVGKUWRSXHYJNHCNSERAYRGKMEJUEPYLOHYKDLCKAYYJOVMGDSDLRITSBMYFMIYDDIPFKXGNOPWADMQUKPAMVERWNFWXSRBAXKRZOQCSXSDSNERSCIRXSRBAXKRZOHGXPIPWXGCGPIYURHYLKTMAXXRGDLCEOELKAYYJSRELRIBAPJCJORAWCEBVSRELRIKLYKCLRIPVSZGVSRETIXFWXYKTOVMXZSGFDWGFDLCVKXYKOXJWCWYFNJGFNMLYDLCKAYYJOVMGDWRSXHYJNHCNSERAYRGKSQNGBXYFDFCUKYQWSXASXLCDZYQWBWYKCIQKBMQCMSLKSHCJKRGFFIQLWILLYTRAYRUADLYFKZCJKKCSXRSSVVCLEVLGPTCJIIYJRSUWFIPLRMQSFIPSQIUSCHCJSZCVPVMEDLCHKWRLRVCWIIYJBIRMBRQGPQYFIZYDEIQTIGYDMYJSDMLYDLCKDELVKVBVOZGSDMMFKRBMXHCJCXYFNMLYISSJVSUDSOCDSLMGNSDSMXSSVPWSFIPSQMLYSRYFIWGFQPCYSZCFIIYJISSJLIRLOVYJWIBLYQYCOMLXYVKWNHCUSWGGXWYFNVCUYKLAJMLYERBWBPWAXKPACOQLKRBSBHBWFMYLSSLACGYDMYJSDIBSCXFWCUSSBIPGYXMXDLCNKVGSXGCSVXCJXERAFIJQSXGKMEJUEPYLOHZQPMLVSRELRIKWKRMXKHYLKWCLPMLVSRELRIBAPJCJORAWYJCSMLBSDENGSRRLYXFWWIYFCUSSBMLYDLCVSJDWBILUOWYVNMLYDLCEDSEWDLCJNMTANMLYLCRZORSELIPGPTMAXXQAXXFWNERSCIRDOWQSXHDAXHGFQXFWCUSSBIPGYXQLKRBSBHBWFMYLSSLACMKHYVRSXXZWMESKOMRUKRFWVTSKOVQSCWCKCVGKUGMFCMBWBELAXZCKDQCFDSNLSSLOSXFSXETWBEEWKRLMKPPWDYPFYJNWBCCSBLMOOZCJDLGKKZCJKKCOKWBWBMTWNJPGWXFWZEQLDLPWOCCSBVCLEVLKYJKSXCTSVYCKLCASVGSDKXGFQXFWCXYFNEPVNITAKXGGXELVERBWBWRSXHGFQCMMBPMOVMIWVMFGYHMXKGRMKPJQKZCJKKGFQMLSXCQAXKJWQMTWXCCSBCMMBFCLDIPSBQCVDSKSUIGFPSPEOHBWMMQAYRQSXHPWMSEFSDGFQYLVOVJQSREJSWIKDELVKVBVOZGSDMMFSWASVGSDKXCVKWRZOWOMKVCJYSRGPXFWFEPAKRAWKPRWBRYLSZCDIMRACGYDMYJSDIBTIJGFNMLYDLCEOELGPEBSDEQWDJGFNMLYDLCVSJDWBILUOSDWKGFVKXYHYMLLDSRZOQCSXWOMKVGFQXFWNMDXOVCFMIQSNHGFQXFWWXMYOXFWBHGNSHGFQFWLRILMWFCJYJNGSRRKSRRZOHYLKWCLVIQKKRBXSRBAXKRZOWOMKVCJYSRKDELVKVBVOZGSDMMFSWGEZSPLKRRTOGYMCIGLMELZOPNMCIPKKWQWCWPACOAGXWGVOVYFSRTWCXKWXXMHDMMFGMRZKRYNOVYYOELFEEJJOXSJXSDHOVWWKVFGGITWBXFACETWBEEWGEQVOVGNOHDJYQRZOTYKDXFJOIWWKVPWDYPFCSDEKRWNKPSWCFWUKPAMVERAXKRZOWRSXHYJNHCNSERAYRYFNYLVOVQLKRBAXKWGEVJGGPGCOPGZYSBGPEALEEJDIETWBEEAXKGFKRWKSREDOKGNORWWKVWGEVZWDXCJKVKWNXMEKOCAXJMJWIBVOGGKSSLKKRBJOGMYXMXAXKSFNIPDIMLYBMQCCXYFNEPVNITAKXGGXMQUKPAMVERWNEQLRIQIEEPWBSMLYJRZOZYJSELUOEJLOVLSDMTWVCGLSWASVGSDKXCVLCDAXHGFQXFWWIYFYJYVKXYKOXDAXHGFQXFWNMDXOVCFMIMXOEAZNERSZSGFDXMLRIKWKRQIEEPAXKRZOHGXPIPWXGCKKHBAXKRZOQRGQIRZOVBAFMBAXKZQDLCFEQZWBSDHYMLLCMLLRIBSDEQWDPCKCELVPMLVSRELRIQIEEPWBSMLCXYFNEPVNITAKXGGXMQAWTMJDELLLIASEWCADGYFRIJHEWCJCEQKOWQJSWIUYRQANIPSXMLNOWREORRGZXGGXAGLRELSFIPSQIYFXYYDBIRMBRMXZIPQOEPZYACNOVRZSWYNOVYYOAYKNIPAFIBXBSKLRINSCXRZBICQOEPJOXSJXWMXWELQFEJMOWZQMEJUEPYLSRELRIQLKRBSBHBWFMYLSSLSXHSFNIPKDELVSREQYYPDYAJAUIJARSMVYJYUDYYDVCYNOVYYSREAXELQCMLYVIEAFILQOEPQYYPTOXRWBEPEOHRGWEIWSRDGBQCVNIAACMMFCELVBIAGQRGRSREMXHCJVCGFQVGKUWRSXHYJNHCNSERAYRGKMEJUEPYLOHYKDLCKAYYJOVMGDSDLRITSBMYFMIYDDIPFKXGNOPWADMQUKPAMVERWNFWXSRBAXKRZOQCSXSDSNERSCIRXSRBAXKRZOHGXPIPWXGCGPIYURHYLKTMAXXRGDLCEOELKAYYJSRELRIBAPJCJORAWCEBVSRELRIKLYKCLRIPVSZGVSRETIXFWXYKTOVMXZSGFDWGFDLCVKXYKOXJWCWYFNJGFNMLYDLCKAYYJOVMGDWRSXHYJNHCNSERAYRGKSQNGBXYFDFCUKYQWSXASXLCDZYQWBWYKCIQKBMQCMSLKSHCJKRGFFIQLWILLYTRAYRUADLYFKZCJKKCSXRSSVVCLEVLGPTCJIIYJRSUWFIPLRMQSFIPSQIUSCHCJSZCVPVMEDLCHKWRLRVCWIIYJBIRMBRQGPQYFIZYDEIQTIGYDMYJSDMLYDLCKDELVKVBVOZGSDMMFKRBMXHCJCXYFNMLYISSJVSUDSOCDSLMGNSDSMXSSVPWSFIPSQMLYSRYFIWGFQPCYSZCFIIYJISSJLIRLOVYJWIBLYQYCOMLXYVKWNHCUSWGGXWYFNVCUYKLAJMLYERBWBPWAXKPACOQLKRBSBHBWFMYLSSLACGYDMYJSDIBSCXFWCUSSBIPGYXMXDLCNKVGSXGCSVXCJXERAFIJQSXGKMEJUEPYLOHZQPMLVSRELRIKWKRMXKHYLKWCLPMLVSRELRIBAPJCJORAWYJCSMLBSDENGSRRLYXFWWIYFCUSSBMLYDLCVSJDWBILUOWYVNMLYDLCEDSEWDLCJNMTANMLYLCRZORSELIPGPTMAXXQAXXFWNERSCIRDOWQSXHDAXHGFQXFWCUSSBIPGYXQLKRBSBHBWFMYLSSLACMKHYVRSXXZWMESKOMRUKRFWVTSKOVQSCWCKCVGKUGMFCMBWBELAXZCKDQCFDSNLSSLOSXFSXETWBEEWKRLMKPPWDYPFYJNWBCCSBLMOOZCJDLGKKZCJKKCOKWBWBMTWNJPGWXFWZEQLDLPWOCCSBVCLEVLKYJKSXCTSVYCKLCASVGSDKXGFQXFWCXYFNEPVNITAKXGGXELVERBWBWRSXHGFQCMMBPMOVMIWVMFGYHMXKGRMKPJQKZCJKKGFQMLSXCQAXKJWQMTWXCCSBCMMBFCLDIPSBQCVDSKSUIGFPSPEOHBWMMQAYRQSXHPWMSEFSDGFQYLVOVJQSREJSWIKDELVKVBVOZGSDMMFSWASVGSDKXCVKWRZOWOMKVCJYSRGPXFWFEPAKRAWKPRWBRYLSZCDIMRACGYDMYJSDIBTIJGFNMLYDLCEOELGPEBSDEQWDJGFNMLYDLCVSJDWBILUOSDWKGFVKXYHYMLLDSRZOQCSXWOMKVGFQXFWNMDXOVCFMIQSNHGFQXFWWXMYOXFWBHGNSHGFQFWLRILMWFCJYJNGSRRKSRRZOHYLKWCLVIQKKRBXSRBAXKRZOWOMKVCJYSRKDELVKVBVOZGSDMMFSWGEZSPLKRRTOGYMCIGLMELZOPNMCIPKKWQWCWPACOAGXWGVOVYFSRTWCXKWXXMHDMMFGMRZKRYNOVYYOELFEEJJOXSJXSDHOVWWKVFGGITWBXFACETWBEEWGEQVOVGNOHDJYQRZOTYKDXFJOIWWKVPWDYPFCSDEKRWNKPSWCFWUKPAMVERAXKRZOWRSXHYJNHCNSERAYRYFNYLVOVQLKRBAXKWGEVJGGPGCOPGZYSBGPEALEEJDIETWBEEAXKGFKRWKSREDOKGNORWWKVWGEVZWDXCJKVKWNXMEKOCAXJMJWIBVOGGKSSLKKRBJOGMYXMXAXKSFNIPDIMLYBMQCCXYFNEPVNITAKXGGXMQUKPAMVERWNEQLRIQIEEPWBSMLYJRZOZYJSELUOEJLOVLSDMTWVCGLSWASVGSDKXCVLCDAXHGFQXFWWIYFYJYVKXYKOXDAXHGFQXFWNMDXOVCFMIMXOEAZNERSZSGFDXMLRIKWKRQIEEPAXKRZOHGXPIPWXGCKKHBAXKRZOQRGQIRZOVBAFMBAXKZQDLCFEQZWBSDHYMLLCMLLRIBSDEQWDPCKCELVPMLVSRELRIQIEEPWBSMLCXYFNEPVNITAKXGGXMQAWTMJDELLLIASEWCADGYFRIJHEWCJCEQKOWQJSWIUYRQANIPSXMLNOWREORRGZXGGXAGLRELSFIPSQIYFXYYDBIRMBRMXZIPQOEPZYACNOVRZSWYNOVYYOAYKNIPAFIBXBSKLRINSCXRZBICQOEPJOXSJXWMXWELQFEJMOWZQMEJUEPYLSRELRIQLKRBSBHBWFMYLSSLSXHSFNIPKDELVSREQYYPDYAJAUIJARSMVYJYUDYYDVCYNOVYYSREAXELQCMLYVIEAFILQOEPQYYPTOXRWBEPEOHRGWEIWSRDGBQCVNIAACMMFCELVBIAGQRGRSREMXHCJVCGFQVGKUWRSXHYJNHCNSERAYRGKMEJUEPYLOHYKDLCKAYYJOVMGDSDLRITSBMYFMIYDDIPFKXGNOPWADMQUKPAMVERWNFWXSRBAXKRZOQCSXSDSNERSCIRXSRBAXKRZOHGXPIPWXGCGPIYURHYLKTMAXXRGDLCEOELKAYYJSRELRIBAPJCJORAWCEBVSRELRIKLYKCLRIPVSZGVSRETIXFWXYKTOVMXZSGFDWGFDLCVKXYKOXJWCWYFNJGFNMLYDLCKAYYJOVMGDWRSXHYJNHCNSERAYRGKSQNGBXYFDFCUKYQWSXASXLCDZYQWBWYKCIQKBMQCMSLKSHCJKRGFFIQLWILLYTRAYRUADLYFKZCJKKCSXRSSVVCLEVLGPTCJIIYJRSUWFIPLRMQSFIPSQIUSCHCJSZCVPVMEDLCHKWRLRVCWIIYJBIRMBRQGPQYFIZYDEIQTIGYDMYJSDMLYDLCKDELVKVBVOZGSDMMFKRBMXHCJCXYFNMLYISSJVSUDSOCDSLMGNSDSMXSSVPWSFIPSQMLYSRYFIWGFQPCYSZCFIIYJISSJLIRLOVYJWIBLYQYCOMLXYVKWNHCUSWGGXWYFNVCUYKLAJMLYERBWBPWAXKPACO";
    int key = guess_key_length(encrypted);
    printf("%d",key);

return 0;    
}